export const mockCategories = [
  {
    id: 'cat-1',
    name: 'Appetizers',
    description: 'Starters and small bites',
  },
  {
    id: 'cat-2',
    name: 'Main Courses',
    description: 'Entrees and main dishes',
  },
  {
    id: 'cat-3',
    name: 'Desserts',
    description: 'Sweet treats and desserts',
  },
  {
    id: 'cat-4',
    name: 'Beverages',
    description: 'Drinks and beverages',
  },
];

export const mockMenuItems = [
  {
    id: 'item-1',
    name: 'Bruschetta',
    description: 'Toasted bread with tomato, garlic, and basil',
    price: 8.99,
    category: 'cat-1',
    available: true,
  },
  {
    id: 'item-2',
    name: 'Calamari Fritti',
    description: 'Crispy fried squid with marinara sauce',
    price: 12.99,
    category: 'cat-1',
    available: true,
  },
  {
    id: 'item-3',
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, tomato, and basil on thin crust',
    price: 14.99,
    category: 'cat-2',
    available: true,
  },
  {
    id: 'item-4',
    name: 'Grilled Salmon',
    description: 'Atlantic salmon with lemon butter sauce and seasonal vegetables',
    price: 24.99,
    category: 'cat-2',
    available: true,
  },
  {
    id: 'item-5',
    name: 'Ribeye Steak',
    description: '12oz premium ribeye with garlic mashed potatoes',
    price: 32.99,
    category: 'cat-2',
    available: false,
  },
  {
    id: 'item-6',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with mascarpone and espresso',
    price: 7.99,
    category: 'cat-3',
    available: true,
  },
  {
    id: 'item-7',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center and vanilla ice cream',
    price: 8.99,
    category: 'cat-3',
    available: true,
  },
  {
    id: 'item-8',
    name: 'Espresso',
    description: 'Single or double shot of premium espresso',
    price: 3.99,
    category: 'cat-4',
    available: true,
  },
  {
    id: 'item-9',
    name: 'House Wine',
    description: 'Selection of red or white house wine',
    price: 6.99,
    category: 'cat-4',
    available: true,
  },
];