export const mockReservations = [
  {
    id: 'RES-001',
    date: '2024-01-15',
    guestName: 'John Smith',
    roomNumber: 101,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-002',
    date: '2024-01-15',
    guestName: 'Sarah Johnson',
    roomNumber: 102,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-003',
    date: '2024-01-15',
    guestName: 'Michael Brown',
    roomNumber: 103,
    status: 'pending' as const,
  },
  {
    id: 'RES-004',
    date: '2024-01-15',
    guestName: 'Emily Davis',
    roomNumber: 104,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-005',
    date: '2024-01-16',
    guestName: 'Robert Wilson',
    roomNumber: 201,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-006',
    date: '2024-01-16',
    guestName: 'Jennifer Martinez',
    roomNumber: 202,
    status: 'cancelled' as const,
  },
  {
    id: 'RES-007',
    date: '2024-01-16',
    guestName: 'David Anderson',
    roomNumber: 203,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-008',
    date: '2024-01-17',
    guestName: 'Lisa Taylor',
    roomNumber: 301,
    status: 'pending' as const,
  },
  {
    id: 'RES-009',
    date: '2024-01-17',
    guestName: 'James Thomas',
    roomNumber: 302,
    status: 'confirmed' as const,
  },
  {
    id: 'RES-010',
    date: '2024-01-18',
    guestName: 'Patricia Jackson',
    roomNumber: 401,
    status: 'confirmed' as const,
  },
];