export const mockReservations = [
  {
    id: '1',
    guestName: 'John Smith',
    email: 'john.smith@example.com',
    checkInDate: '2024-02-15',
    checkOutDate: '2024-02-18',
    roomType: 'Deluxe Suite',
    numberOfGuests: 2,
    totalPrice: 450,
    confirmationNumber: 'RES-2024-001',
    status: 'pending' as const,
    location: 'New York, NY',
  },
  {
    id: '2',
    guestName: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    checkInDate: '2024-02-20',
    checkOutDate: '2024-02-25',
    roomType: 'Ocean View Room',
    numberOfGuests: 3,
    totalPrice: 750,
    confirmationNumber: 'RES-2024-002',
    status: 'confirmed' as const,
    location: 'Miami, FL',
  },
  {
    id: '3',
    guestName: 'Michael Chen',
    email: 'm.chen@example.com',
    checkInDate: '2024-03-01',
    checkOutDate: '2024-03-05',
    roomType: 'Standard Room',
    numberOfGuests: 1,
    totalPrice: 320,
    confirmationNumber: 'RES-2024-003',
    status: 'sent' as const,
    location: 'Los Angeles, CA',
  },
  {
    id: '4',
    guestName: 'Emily Rodriguez',
    email: 'emily.r@example.com',
    checkInDate: '2024-03-10',
    checkOutDate: '2024-03-12',
    roomType: 'Family Suite',
    numberOfGuests: 4,
    totalPrice: 580,
    confirmationNumber: 'RES-2024-004',
    status: 'pending' as const,
    location: 'Chicago, IL',
  },
  {
    id: '5',
    guestName: 'David Williams',
    email: 'david.w@example.com',
    checkInDate: '2024-03-15',
    checkOutDate: '2024-03-17',
    roomType: 'Premium Suite',
    numberOfGuests: 2,
    totalPrice: 620,
    confirmationNumber: 'RES-2024-005',
    status: 'confirmed' as const,
    location: 'Boston, MA',
  },
];