export const mockDishes = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic Italian pizza with fresh mozzarella, basil, and tomato sauce on a crispy crust.',
    category: 'Italian',
    prepTime: '25 mins',
    servings: 2,
    ingredients: [
      { id: '1-1', name: 'Pizza Dough', quantity: '500g' },
      { id: '1-2', name: 'Tomato Sauce', quantity: '200ml' },
      { id: '1-3', name: 'Fresh Mozzarella', quantity: '250g' },
      { id: '1-4', name: 'Fresh Basil', quantity: '10 leaves' },
      { id: '1-5', name: 'Olive Oil', quantity: '2 tbsp' },
      { id: '1-6', name: 'Salt & Pepper', quantity: 'to taste' },
    ],
  },
  {
    id: '2',
    name: 'Pad Thai',
    description: 'Authentic Thai stir-fried noodles with shrimp, tofu, and a perfect balance of sweet, sour, and spicy flavors.',
    category: 'Thai',
    prepTime: '20 mins',
    servings: 2,
    ingredients: [
      { id: '2-1', name: 'Rice Noodles', quantity: '300g' },
      { id: '2-2', name: 'Shrimp', quantity: '200g' },
      { id: '2-3', name: 'Tofu', quantity: '150g' },
      { id: '2-4', name: 'Tamarind Paste', quantity: '3 tbsp' },
      { id: '2-5', name: 'Fish Sauce', quantity: '2 tbsp' },
      { id: '2-6', name: 'Peanuts', quantity: '50g' },
      { id: '2-7', name: 'Lime', quantity: '1' },
    ],
  },
  {
    id: '3',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with homemade Caesar dressing, croutons, and Parmesan cheese.',
    category: 'Salad',
    prepTime: '15 mins',
    servings: 1,
    ingredients: [
      { id: '3-1', name: 'Romaine Lettuce', quantity: '200g' },
      { id: '3-2', name: 'Parmesan Cheese', quantity: '50g' },
      { id: '3-3', name: 'Croutons', quantity: '100g' },
      { id: '3-4', name: 'Caesar Dressing', quantity: '100ml' },
      { id: '3-5', name: 'Lemon', quantity: '1/2' },
      { id: '3-6', name: 'Black Pepper', quantity: 'to taste' },
    ],
  },
  {
    id: '4',
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in soft tortillas with fresh toppings and zesty lime crema.',
    category: 'Mexican',
    prepTime: '18 mins',
    servings: 3,
    ingredients: [
      { id: '4-1', name: 'Ground Beef', quantity: '400g' },
      { id: '4-2', name: 'Soft Tortillas', quantity: '6' },
      { id: '4-3', name: 'Onion', quantity: '1' },
      { id: '4-4', name: 'Cilantro', quantity: '20g' },
      { id: '4-5', name: 'Lime', quantity: '2' },
      { id: '4-6', name: 'Sour Cream', quantity: '100ml' },
      { id: '4-7', name: 'Cumin', quantity: '1 tsp' },
    ],
  },
  {
    id: '5',
    name: 'Sushi Roll',
    description: 'Delicate sushi rolls with fresh salmon, avocado, and cucumber, served with wasabi and soy sauce.',
    category: 'Japanese',
    prepTime: '30 mins',
    servings: 2,
    ingredients: [
      { id: '5-1', name: 'Sushi Rice', quantity: '300g' },
      { id: '5-2', name: 'Nori Sheets', quantity: '4' },
      { id: '5-3', name: 'Fresh Salmon', quantity: '200g' },
      { id: '5-4', name: 'Avocado', quantity: '1' },
      { id: '5-5', name: 'Cucumber', quantity: '1' },
      { id: '5-6', name: 'Wasabi', quantity: '1 tbsp' },
      { id: '5-7', name: 'Soy Sauce', quantity: '50ml' },
    ],
  },
  {
    id: '6',
    name: 'Coq au Vin',
    description: 'French braised chicken in red wine with mushrooms, pearl onions, and bacon.',
    category: 'French',
    prepTime: '90 mins',
    servings: 4,
    ingredients: [
      { id: '6-1', name: 'Chicken Pieces', quantity: '1.2kg' },
      { id: '6-2', name: 'Red Wine', quantity: '500ml' },
      { id: '6-3', name: 'Bacon', quantity: '150g' },
      { id: '6-4', name: 'Mushrooms', quantity: '300g' },
      { id: '6-5', name: 'Pearl Onions', quantity: '250g' },
      { id: '6-6', name: 'Garlic', quantity: '4 cloves' },
      { id: '6-7', name: 'Thyme', quantity: '2 sprigs' },
    ],
  },
];