export const mockDishes = [
  {
    id: '1',
    name: 'Margherita Pizza',
    description: 'Classic Italian pizza with fresh mozzarella, basil, and tomato sauce on a thin crust. A timeless favorite that celebrates simplicity and quality ingredients.',
    category: 'Italian',
    prepTime: '25 mins',
    ingredients: [
      { id: '1-1', name: 'Pizza Dough', quantity: '500g' },
      { id: '1-2', name: 'Tomato Sauce', quantity: '200ml' },
      { id: '1-3', name: 'Fresh Mozzarella', quantity: '250g' },
      { id: '1-4', name: 'Fresh Basil', quantity: '10 leaves' },
      { id: '1-5', name: 'Olive Oil', quantity: '3 tbsp' },
      { id: '1-6', name: 'Sea Salt', quantity: 'to taste' },
    ],
  },
  {
    id: '2',
    name: 'Pad Thai',
    description: 'Authentic Thai stir-fried noodles with shrimp, tofu, and vegetables. Balanced flavors of sweet, sour, salty, and spicy in every bite.',
    category: 'Thai',
    prepTime: '20 mins',
    ingredients: [
      { id: '2-1', name: 'Rice Noodles', quantity: '300g' },
      { id: '2-2', name: 'Shrimp', quantity: '200g' },
      { id: '2-3', name: 'Tofu', quantity: '150g' },
      { id: '2-4', name: 'Tamarind Paste', quantity: '3 tbsp' },
      { id: '2-5', name: 'Fish Sauce', quantity: '2 tbsp' },
      { id: '2-6', name: 'Peanuts', quantity: '50g' },
      { id: '2-7', name: 'Lime', quantity: '1' },
    ],
  },
  {
    id: '3',
    name: 'Beef Tacos',
    description: 'Seasoned ground beef in soft corn tortillas topped with fresh lettuce, tomato, cheese, and sour cream. A Mexican favorite that is quick and satisfying.',
    category: 'Mexican',
    prepTime: '15 mins',
    ingredients: [
      { id: '3-1', name: 'Ground Beef', quantity: '400g' },
      { id: '3-2', name: 'Corn Tortillas', quantity: '8 pieces' },
      { id: '3-3', name: 'Lettuce', quantity: '100g' },
      { id: '3-4', name: 'Tomato', quantity: '2 medium' },
      { id: '3-5', name: 'Cheddar Cheese', quantity: '150g' },
      { id: '3-6', name: 'Sour Cream', quantity: '100ml' },
      { id: '3-7', name: 'Taco Seasoning', quantity: '2 tbsp' },
    ],
  },
  {
    id: '4',
    name: 'Sushi Roll',
    description: 'Delicate sushi rolls with fresh salmon, cucumber, and avocado wrapped in nori. Served with soy sauce, wasabi, and pickled ginger for an authentic Japanese experience.',
    category: 'Japanese',
    prepTime: '30 mins',
    ingredients: [
      { id: '4-1', name: 'Sushi Rice', quantity: '300g' },
      { id: '4-2', name: 'Nori Sheets', quantity: '4 sheets' },
      { id: '4-3', name: 'Fresh Salmon', quantity: '200g' },
      { id: '4-4', name: 'Cucumber', quantity: '1' },
      { id: '4-5', name: 'Avocado', quantity: '1' },
      { id: '4-6', name: 'Soy Sauce', quantity: '50ml' },
      { id: '4-7', name: 'Wasabi', quantity: '1 tbsp' },
    ],
  },
  {
    id: '5',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with homemade Caesar dressing, parmesan cheese, and croutons. A light yet satisfying dish perfect for lunch or as a side.',
    category: 'Salad',
    prepTime: '10 mins',
    ingredients: [
      { id: '5-1', name: 'Romaine Lettuce', quantity: '300g' },
      { id: '5-2', name: 'Parmesan Cheese', quantity: '100g' },
      { id: '5-3', name: 'Croutons', quantity: '100g' },
      { id: '5-4', name: 'Caesar Dressing', quantity: '150ml' },
      { id: '5-5', name: 'Lemon', quantity: '1' },
      { id: '5-6', name: 'Black Pepper', quantity: 'to taste' },
    ],
  },
  {
    id: '6',
    name: 'Chicken Tikka Masala',
    description: 'Tender chicken pieces in a creamy tomato-based curry sauce with aromatic spices. Served with basmati rice or naan bread for an Indian culinary delight.',
    category: 'Indian',
    prepTime: '40 mins',
    ingredients: [
      { id: '6-1', name: 'Chicken Breast', quantity: '600g' },
      { id: '6-2', name: 'Yogurt', quantity: '200ml' },
      { id: '6-3', name: 'Tomato Sauce', quantity: '400ml' },
      { id: '6-4', name: 'Ginger-Garlic Paste', quantity: '3 tbsp' },
      { id: '6-5', name: 'Garam Masala', quantity: '2 tsp' },
      { id: '6-6', name: 'Cream', quantity: '100ml' },
      { id: '6-7', name: 'Cilantro', quantity: '20g' },
    ],
  },
];