export const mockChefRecommendations = [
  {
    id: '1',
    name: 'Pan-Seared Salmon',
    description: 'Fresh Atlantic salmon with lemon butter sauce, served with seasonal vegetables and wild rice',
    price: 28.99,
    isChefRecommendation: true,
    category: 'Main Course',
  },
  {
    id: '2',
    name: 'Truffle Risotto',
    description: 'Creamy Arborio rice with black truffle, Parmesan, and wild mushrooms',
    price: 24.99,
    isChefRecommendation: true,
    category: 'Main Course',
  },
  {
    id: '3',
    name: 'Beef Tenderloin',
    description: 'Prime cut beef with red wine reduction, roasted potatoes, and asparagus',
    price: 35.99,
    isChefRecommendation: true,
    category: 'Main Course',
  },
  {
    id: '4',
    name: 'Grilled Branzino',
    description: 'Mediterranean sea bass with olive tapenade, heirloom tomatoes, and basil oil',
    price: 32.99,
    isChefRecommendation: false,
    category: 'Main Course',
  },
  {
    id: '5',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, vanilla ice cream, and fresh berries',
    price: 9.99,
    isChefRecommendation: true,
    category: 'Dessert',
  },
  {
    id: '6',
    name: 'Burrata Salad',
    description: 'Creamy burrata cheese, heirloom tomatoes, arugula, and aged balsamic',
    price: 14.99,
    isChefRecommendation: false,
    category: 'Appetizer',
  },
];