export const mockMenuItems = [
  {
    id: '1',
    name: 'Pan-Seared Salmon',
    description: 'Fresh Atlantic salmon with lemon butter sauce',
    price: 28.99,
    category: 'Main Course',
    isChefRecommendation: true,
  },
  {
    id: '2',
    name: 'Truffle Risotto',
    description: 'Creamy arborio rice with black truffle and parmesan',
    price: 24.99,
    category: 'Main Course',
    isChefRecommendation: true,
  },
  {
    id: '3',
    name: 'Grilled Ribeye Steak',
    description: '16oz prime cut with roasted vegetables',
    price: 42.99,
    category: 'Main Course',
    isChefRecommendation: false,
  },
  {
    id: '4',
    name: 'Burrata Salad',
    description: 'Fresh burrata cheese with heirloom tomatoes and basil',
    price: 16.99,
    category: 'Appetizer',
    isChefRecommendation: true,
  },
  {
    id: '5',
    name: 'Shrimp Scampi',
    description: 'Gulf shrimp in garlic white wine sauce with pasta',
    price: 26.99,
    category: 'Main Course',
    isChefRecommendation: false,
  },
  {
    id: '6',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center and vanilla ice cream',
    price: 12.99,
    category: 'Dessert',
    isChefRecommendation: false,
  },
  {
    id: '7',
    name: 'Beef Carpaccio',
    description: 'Thinly sliced raw beef with capers and arugula',
    price: 18.99,
    category: 'Appetizer',
    isChefRecommendation: false,
  },
  {
    id: '8',
    name: 'Duck Confit',
    description: 'Slow-cooked duck leg with cherry gastrique',
    price: 32.99,
    category: 'Main Course',
    isChefRecommendation: true,
  },
];