export const menuMockData = [
  {
    id: '1',
    name: 'Bruschetta',
    description: 'Toasted bread with tomato, garlic, and basil',
    price: 8.99,
    category: 'Starters' as const,
    isVegan: true,
    isSpicy: false,
  },
  {
    id: '2',
    name: 'Calamari Fritti',
    description: 'Crispy fried squid with lemon aioli',
    price: 12.99,
    category: 'Starters' as const,
    isVegan: false,
    isSpicy: false,
  },
  {
    id: '3',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomato, and basil with balsamic glaze',
    price: 10.99,
    category: 'Starters' as const,
    isVegan: true,
    isSpicy: false,
  },
  {
    id: '4',
    name: 'Grilled Salmon',
    description: 'Atlantic salmon fillet with seasonal vegetables and lemon butter',
    price: 24.99,
    category: 'Main' as const,
    isVegan: false,
    isSpicy: false,
  },
  {
    id: '5',
    name: 'Pasta Carbonara',
    description: 'Creamy pasta with pancetta, egg, and Pecorino Romano',
    price: 16.99,
    category: 'Main' as const,
    isVegan: false,
    isSpicy: false,
  },
  {
    id: '6',
    name: 'Vegetable Risotto',
    description: 'Creamy arborio rice with seasonal vegetables and truffle oil',
    price: 18.99,
    category: 'Main' as const,
    isVegan: true,
    isSpicy: false,
  },
  {
    id: '7',
    name: 'Thai Green Curry',
    description: 'Chicken in aromatic green curry with coconut milk and basil',
    price: 17.99,
    category: 'Main' as const,
    isVegan: false,
    isSpicy: true,
  },
  {
    id: '8',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, served with vanilla ice cream',
    price: 9.99,
    category: 'Desserts' as const,
    isVegan: false,
    isSpicy: false,
  },
  {
    id: '9',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with mascarpone, espresso, and cocoa',
    price: 8.99,
    category: 'Desserts' as const,
    isVegan: false,
    isSpicy: false,
  },
  {
    id: '10',
    name: 'Vegan Cheesecake',
    description: 'Creamy cashew-based cheesecake with berry compote',
    price: 10.99,
    category: 'Desserts' as const,
    isVegan: true,
    isSpicy: false,
  },
];