export const mockNewDishes = [
  {
    id: '1',
    name: 'Truffle Risotto',
    description: 'Creamy arborio rice with black truffle, parmesan, and wild mushrooms',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1476124369162-f4978d1b89e9?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '2',
    name: 'Miso-Glazed Salmon',
    description: 'Pan-seared salmon with miso glaze, served with jasmine rice and bok choy',
    price: 28.50,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '3',
    name: 'Burrata & Heirloom Tomato',
    description: 'Fresh burrata cheese with colorful heirloom tomatoes, basil oil, and balsamic reduction',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Appetizer',
  },
  {
    id: '4',
    name: 'Spiced Lamb Tagine',
    description: 'Slow-cooked lamb with apricots, almonds, and warm spices served with couscous',
    price: 26.75,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '5',
    name: 'Crispy Tofu Banh Mi',
    description: 'Crispy tofu, pickled vegetables, cilantro, and sriracha mayo on a crusty baguette',
    price: 14.50,
    image: 'https://images.unsplash.com/photo-1585238341710-4913d3a3a48f?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Sandwich',
  },
  {
    id: '6',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, served with vanilla ice cream and berries',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
    isNew: true,
    category: 'Dessert',
  },
];