export const mockNewDishes = [
  {
    id: '1',
    name: 'Truffle Risotto',
    description: 'Creamy arborio rice with black truffle, parmesan, and wild mushrooms',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1476124369162-f4978d1b89d9?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '2',
    name: 'Miso Glazed Salmon',
    description: 'Pan-seared salmon with miso glaze, served with jasmine rice and bok choy',
    price: 28.50,
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '3',
    name: 'Burrata & Heirloom Tomato',
    description: 'Fresh burrata cheese with heirloom tomatoes, basil oil, and balsamic reduction',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Appetizer',
  },
  {
    id: '4',
    name: 'Saffron Paella',
    description: 'Traditional Spanish paella with saffron, seafood, and roasted vegetables',
    price: 32.00,
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561404?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
  {
    id: '5',
    name: 'Matcha Tiramisu',
    description: 'Japanese green tea matcha layered with mascarpone cream and ladyfingers',
    price: 12.50,
    image: 'https://images.unsplash.com/photo-1571115177098-24ec42ed204d?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Dessert',
  },
  {
    id: '6',
    name: 'Crispy Duck Confit',
    description: 'Slow-cooked duck leg with crispy skin, served with cherry gastrique and root vegetables',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500&h=400&fit=crop',
    isNew: true,
    category: 'Main Course',
  },
];